In [2]:
from gensim.models import KeyedVectors
from numpy.ma.core import negative

model_path = './data/sgns.weibo.word'
model = KeyedVectors.load_word2vec_format(model_path)

In [3]:
print(model.vector_size)

300


In [4]:
print(model['地铁'])

[ 2.92064e-01 -5.18680e-02 -2.13720e-01  1.82131e-01  2.82900e-03
  4.14104e-01  1.56440e-01 -1.27940e-02 -3.28332e-01 -8.25000e-02
 -8.46890e-02 -2.14700e-02  1.18650e-01 -4.73659e-01 -1.97850e-02
  1.13939e-01  1.82734e-01 -6.46420e-02  5.60832e-01 -6.65230e-02
 -1.97960e-01  1.26039e-01 -3.28720e-01 -3.09730e-02 -3.46580e-01
 -1.53190e-01 -2.96226e-01 -5.75517e-01  1.10684e-01  8.19220e-02
 -1.04721e-01 -1.77477e-01 -1.21332e-01  1.49816e-01  2.86278e-01
 -8.11200e-03  6.72540e-02  6.92220e-02 -3.50973e-01 -5.49500e-02
 -7.80250e-02 -1.92952e-01 -1.70920e-01 -1.28289e-01  1.08204e-01
 -7.24913e-01 -1.11735e-01 -6.75000e-03  4.38086e-01 -8.75720e-02
 -1.41320e-01 -1.91726e-01  1.68363e-01 -7.85700e-02 -1.79772e-01
 -1.27950e-01  3.24675e-01  2.70616e-01  1.96330e-02 -3.09431e-01
 -4.02670e-02  5.80160e-02 -1.06603e-01  2.48022e-01  2.59204e-01
  2.16016e-01  3.96293e-01  2.48630e-02 -7.63330e-02  6.10183e-01
  2.73094e-01 -1.37777e-01  7.65180e-02 -1.35788e-01 -1.42440e-01
  1.22921e

In [6]:
similarity = model.similarity('地铁', '公交')
print('地铁 vs 公交 相似度：', similarity)

地铁 vs 公交 相似度： 0.65458214


In [8]:
len(model.index_to_key)

195202

In [10]:
model.similarity('地铁', '太阳')

np.float32(0.09804901)

In [12]:
model.most_similar(positive=['男人', '女孩'], negative=['男孩'], topn = 5)

[('女人', 0.6578881740570068),
 ('女孩子', 0.515068531036377),
 ('女生', 0.45194485783576965),
 ('女人真', 0.4420627951622009),
 ('女人们', 0.43698593974113464)]

## 训练自己的词向量

In [13]:
from gensim.models import Word2Vec

sentences = [
    ["我", "喜欢", "机器学习"],
    ["我", "喜欢", "深度学习"],
    ["机器学习", "很", "有趣"],
    ["深度学习", "很", "有趣"],
    ["量子计算"]   # 只出现一次
]



In [14]:
model = Word2Vec(
    sentences,          # 已分词的句子序列
    vector_size=100,    # 词向量维度
    window=5,           # 上下文窗口大小
    min_count=2,        # 最小词频（低于将被忽略）
    sg=1,               # 1: Skip-Gram, 0: CBOW
    workers=4           # 并行训练线程数
)



In [ ]:
# (3) 保存词向量
model.wv.save_word2vec_format('my_vectors.kv')



In [20]:
import pandas as pd
import jieba
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

In [3]:
df = pd.read_csv('./data/online_shopping_10_cats.csv')

In [4]:
df.head()

,cat,label,review
0,书籍,1,做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1,书籍,1,作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2,书籍,1,作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3,书籍,1,作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4,书籍,1,作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...


In [5]:
df['review']

0        做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1        作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2        作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3        作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4        作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...
                               ...                        
62769    我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
62770    房间很小，整体设施老化，和四星的差距很大。毛巾太破旧了。早餐很简陋。房间隔音很差，隔两间房间...
62771                        我感觉不行。。。性价比很差。不知道是银川都这样还是怎么的！
62772    房间时间长，进去有点异味！服务员是不是不够用啊！我在一楼找了半个小时以上才找到自己房间，想找...
62773    老人小孩一大家族聚会，选在吴宫泛太平洋，以为新加坡品牌一定很不错，没想到11点30分到前台，...
Name: review, Length: 62774, dtype: object

In [6]:
df[df['review'].isna()]

,cat,label,review
36425,热水器,1,NaN


In [7]:
df = pd.read_csv('./data/online_shopping_10_cats.csv').dropna()

In [8]:
df['review']

0        做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1        作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2        作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3        作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4        作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...
                               ...                        
62769    我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
62770    房间很小，整体设施老化，和四星的差距很大。毛巾太破旧了。早餐很简陋。房间隔音很差，隔两间房间...
62771                        我感觉不行。。。性价比很差。不知道是银川都这样还是怎么的！
62772    房间时间长，进去有点异味！服务员是不是不够用啊！我在一楼找了半个小时以上才找到自己房间，想找...
62773    老人小孩一大家族聚会，选在吴宫泛太平洋，以为新加坡品牌一定很不错，没想到11点30分到前台，...
Name: review, Length: 62773, dtype: object

In [16]:
sentences = [[token for token in jieba.lcut(sentence) if token.strip() != '']  for sentence in df['review']]

In [17]:
sentences[0:3]

[['做',
  '父母',
  '一定',
  '要',
  '有',
  '刘墉',
  '这样',
  '的',
  '心态',
  '，',
  '不断',
  '地',
  '学习',
  '，',
  '不断',
  '地',
  '进步',
  '，',
  '不断',
  '地',
  '给',
  '自己',
  '补充',
  '新鲜血液',
  '，',
  '让',
  '自己',
  '保持',
  '一颗',
  '年轻',
  '的',
  '心',
  '。',
  '我',
  '想',
  '，',
  '这',
  '是',
  '他',
  '能',
  '很',
  '好',
  '的',
  '和',
  '孩子',
  '沟通',
  '的',
  '一个',
  '重要',
  '因素',
  '。',
  '读',
  '刘墉',
  '的',
  '文章',
  '，',
  '总能',
  '让',
  '我',
  '看到',
  '一个',
  '快乐',
  '的',
  '平易近人',
  '的',
  '父亲',
  '，',
  '他',
  '始终',
  '站',
  '在',
  '和',
  '孩子',
  '同样',
  '的',
  '高度',
  '，',
  '给',
  '孩子',
  '创造',
  '着',
  '一个',
  '充满',
  '爱',
  '和',
  '自由',
  '的',
  '生活',
  '环境',
  '。',
  '很',
  '喜欢',
  '刘墉',
  '在',
  '字里行间',
  '流露出',
  '的',
  '做',
  '父母',
  '的',
  '那种',
  '小',
  '狡黠',
  '，',
  '让',
  '人',
  '总是',
  '忍俊不禁',
  '，',
  '父母',
  '和',
  '子女',
  '之间',
  '有时候',
  '也',
  '是',
  '一种',
  '战斗',
  '，',
  '武力',
  '争斗',
  '过于',
  '低级',
  '了',
  '，',
  '智力',
  '较量',
  '才',
  '更',
  '有',
  '趣味',
  '。',
  '

In [18]:

model = Word2Vec(
    sentences,          # 已分词的句子序列
    vector_size=100,    # 词向量维度
    window=5,           # 上下文窗口大小
    min_count=2,        # 最小词频（低于将被忽略）
    sg=1,               # 1: Skip-Gram, 0: CBOW
    workers=4           # 并行训练线程数
)

In [14]:
model.wv['地铁']

array([ 0.25146398,  0.29204106,  0.08295906,  0.17511508, -0.08025803,
       -0.46069276,  0.29893175,  1.1612579 , -0.14168867,  0.05376106,
       -0.27059972, -0.1378845 , -0.2085184 , -0.02625815,  0.3567058 ,
       -0.38292658,  0.3888726 , -0.62884504,  0.3636912 , -0.09825888,
       -0.03981847, -0.13672003,  0.55010045,  0.46636367, -0.20146826,
       -0.46431118, -0.29440784,  0.18929431, -0.09700701, -0.2140558 ,
        0.22271983,  0.311678  , -0.49374074, -0.3608403 ,  0.10864531,
       -0.18163942,  0.11519855, -0.45058104, -0.02837364, -0.8765359 ,
       -0.0116253 ,  0.04321896,  0.32387212, -0.02356409, -0.17901559,
        0.40114182, -0.20931369, -0.06258011,  0.09363347, -0.20700167,
       -0.16223355, -0.1335011 , -0.6657899 , -0.7118181 , -0.1869058 ,
        0.30522224,  0.06110308,  0.5916828 , -0.14831387, -0.30542803,
        0.1028256 ,  0.2856858 , -0.04322176, -0.04662691, -0.11850881,
        0.49745268,  0.3782197 , -0.24479708, -0.44508117, -0.12

In [22]:
model.wv.save_word2vec_format('./data/word2vec.txt')

In [23]:
KeyedVectors.load_word2vec_format('./data/word2vec.txt', binary=False)

# 第三节 词向量应用

## 步骤
1. 加载词向量
2. 处理OOV
3. 准备词向量矩阵
4. 创建embedding
5.

In [36]:
import torch
import torch.nn as nn
from gensim.models import KeyedVectors
import numpy as np

In [25]:
wv = KeyedVectors.load_word2vec_format('./data/word2vec.txt', binary=False)

In [41]:
unk_token = '<unk>'
index2word = [unk_token] + wv.index_to_key
word2index = {word: index for index, word in enumerate(index2word)}

In [26]:
wv.vector_size

100

In [27]:
len(wv.index_to_key)

34576

In [34]:
print(wv)

KeyedVectors<vector_size=100, 34576 keys>


In [35]:
num_embeddings = len(index2word)
embedding_dim = wv.vector_size
embedding_matrix = torch.randn(num_embeddings, embedding_dim)

for index, token in enumerate(index2word):
    if token in wv:
        embedding_matrix[index] = torch.tensor(wv[token])
# 把存在电脑上的wv持久化的文件读到内存里，第一行作为unknown的token，其他部分照搬，然后得到的embedding_matrix就是第一行是<unk>:vector[1x100] 其余还是预训练的数据

In [38]:
embedding = nn.Embedding.from_pretrained(embedding_matrix)
embedding

Embedding(34576, 100)

In [39]:
text = "我喜欢乘坐地铁"
tokens = jieba.lcut(text)
input_ids = [wv.key_to_index[token] for token in tokens] # 没有处理OOV
input_tensor = torch.tensor(input_ids)
embedding(input_tensor)

tensor([[ 0.2986,  0.1158,  0.1555,  0.2226,  0.0911, -0.8412,  0.3645, -0.0711,
          0.0324,  0.0730,  0.1488, -0.3440,  0.0472, -0.4379, -0.1110, -0.2409,
         -0.0320, -0.3949, -0.1085, -0.4997,  0.4487,  0.1236,  0.4678, -0.4605,
         -0.2762,  0.0197,  0.0331,  0.4818,  0.0248, -0.2162,  0.2693,  0.0513,
         -0.1355,  0.0636, -0.3086,  0.1452,  0.2266, -0.1203, -0.2510, -0.2985,
          0.0499, -0.1507,  0.0285,  0.1857,  0.0668,  0.1513, -0.0015, -0.0168,
          0.1378,  0.0353, -0.2122, -0.0188,  0.2813, -0.0204, -0.3760,  0.2712,
          0.2837, -0.1796, -0.1311,  0.2042,  0.4569, -0.2516, -0.6263, -0.3390,
         -0.3094,  0.4027,  0.1241,  0.5577, -0.4599, -0.2460, -0.0532, -0.2664,
          0.3569, -0.1914, -0.0896,  0.1583,  0.1769, -0.2683, -0.2399, -0.1127,
         -0.4451,  0.1720,  0.0353,  0.4994, -0.1527,  0.0377, -0.0865,  0.1678,
          0.2407, -0.0886, -0.0058, -0.1909, -0.2097,  0.3762,  0.2265, -0.1974,
         -0.1492,  0.0175, -

In [42]:
text = "我喜欢乘坐地铁"
tokens = jieba.lcut(text)
input_ids = [word2index.get(token, word2index[unk_token]) for token in tokens]
input_tensor = torch.tensor(input_ids)
embedding(input_tensor)

tensor([[-3.4813e-01,  1.0072e-01,  3.2521e-01, -3.4149e-01, -3.3096e-02,
         -4.7691e-01,  5.5949e-01,  3.8537e-01, -2.1289e-01,  3.2176e-01,
         -1.1068e-01, -2.1118e-01, -1.3260e-02, -9.4665e-02,  5.4965e-02,
         -1.8843e-01,  2.0984e-01, -1.9970e-01, -3.4867e-01, -1.6420e-01,
         -5.1776e-02,  2.8219e-02,  6.5568e-01, -1.7580e-01, -1.2367e-01,
          4.6072e-01, -3.5287e-02, -1.1235e-01, -1.1620e-01, -2.2572e-01,
          1.5255e-01, -2.6244e-01, -5.8755e-02, -2.4427e-01, -1.5130e-01,
          1.0394e-02,  2.7228e-01,  1.5155e-01,  4.0211e-01, -3.1396e-01,
         -1.4572e-01,  1.2839e-01, -2.2655e-01,  3.7954e-02, -7.9699e-03,
         -1.8070e-01, -2.7984e-01,  3.3744e-01,  1.3283e-01,  4.7475e-01,
         -8.6188e-02, -8.1918e-02,  2.6509e-01, -2.5803e-01, -1.4981e-02,
          3.9479e-01,  4.1536e-01, -1.0327e-01,  2.7353e-01, -4.5549e-02,
          3.7656e-01, -3.6514e-01,  8.6951e-03, -1.1146e-01,  5.1326e-02,
          6.5250e-01, -1.0866e-01,  4.